### ISSUE TITLE
Shape JS insertion / F5 AWAF JS incompatibility

### ISSUE THREAD

**Issue by b3nnnn** [F5Networks/shape-iapp#10]
Using both AWAF PBD and Shape on a single page is incompatible. The iApp by default injects the Shape JS on every URI - regardless of whether its within the iApp configuration as a protected URL. When PBD is also configured using microservice configuration to protect a page that shape is not protecting the Shape JS is also injected - resulting in false positives. I suggest only injecting the Shape JS on pages that Shape is protecting.

**Comment by ohadk** [comment]
You have the option to exclude injection from specific pages. So by that, you can control the pages you want to inject the JS.
Hope I understood you correctly with this issue.

**Comment by b3nnnn** [comment]
Ahh, found it - thank you.
