### ISSUE TITLE
Removing SPDT iApp fails

### ISSUE THREAD

**Issue by b3nnnn** [F5Networks/shape-iapp#2]
01070265:3: The Pool (/Common/SPDT_Pool) cannot be deleted because it is in use by a virtual server clone pool (/Common/XXX-http-vs /Common/SPDT_Pool 2).

Existing VS profile is modified for clone pool - but not cleaned up on deletion.

**Comment by saart91** [comment]
Hi @b3nnnn,
Can you please state the steps you are doing?
Are you trying to delete an iApp application after creation? if so, the deployment guide states that you must detach the clone pool before trying to remove.

**Comment by b3nnnn** [comment]
Creating, then deleting using iApp - it ideally would clean up after it's self rather than require manual steps for cleanup.

**Comment by saart91** [comment]
It cannot delete the SPDT_Pool since its in use with the VS. It's a known limitation, we cannot tell the iApp to detach the pool member and only then delete it.
If you know anything else (without creating a destructor template), I'll be happy to know :)

**Comment by b3nnnn** [comment]
Fair enough
