### ISSUE TITLE
SSL serverside logic for iApp broken for environments without HTTP profile on original VS

### ISSUE THREAD

**Issue by b3nnnn** [F5Networks/shape-iapp#3]
01071912:3: HTTP_REQUEST event in rule (/Common/target_ssl_vip) requires an associated HTTP or FASTHTTP profile on the virtual-server (/Common/mytestvs).

Attempts to apply an iRule that requires a HTTP profile without validating there is one.

**Comment by saart91** [comment]
Fixed in v1.1.0
