### ISSUE TITLE
No-SNAT serverside SSL environments broken 

### ISSUE THREAD

**Issue by b3nnnn** [F5Networks/shape-iapp#4]
For environments where SNAT is not in place and a serverside SSL profile is in place the iApp Migrates to a VIP targeting VIP configuration where the backend VIP uses SNAT.

As a result subsequent requests to webservers will be sourced from the BIGIP's closest interface as the iApp enables SNAT on the backend VS.  This will break webserver logging/be a pretty significant change. Probably needs documentation notes and X-Forwarded-For configuration.

**Comment by saart91** [comment]
Fixed in v1.1.0
